name: teesco
description: Volunteer Management Application from Entrepreneurship Cell, NIT Raipur

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Logging library
  logger: ^0.8.3
  # Http Client generator
  http: ^0.12.1
  # Service Locator (DI)
  get_it: ^4.0.1
  # BLoC (Business Logic Component) for Flutter State Management
  flutter_bloc: ^4.0.0
  # Equating two dart objects
  equatable: ^1.1.1
  # Socket based data connection checker {beta}
  data_connection_checker: ^0.3.4
  # Local Cache Management
  shared_preferences: ^0.5.6+3
  # Common Fonts
  google_fonts: ^0.5.0+1
  # Picking images from the image library
  image_picker: ^0.6.6+5
  transparent_image: ^1.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  # Mock framework
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
